// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/calculator.proto
// Protobuf Java Version: 4.28.2

package pb.calculator;

public final class CalculatorOuterClass {
  private CalculatorOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      CalculatorOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NoParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:calculator.NoParam)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code calculator.NoParam}
   */
  public static final class NoParam extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:calculator.NoParam)
      NoParamOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        NoParam.class.getName());
    }
    // Use NoParam.newBuilder() to construct.
    private NoParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NoParam() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_NoParam_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_NoParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.calculator.CalculatorOuterClass.NoParam.class, pb.calculator.CalculatorOuterClass.NoParam.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.calculator.CalculatorOuterClass.NoParam)) {
        return super.equals(obj);
      }
      pb.calculator.CalculatorOuterClass.NoParam other = (pb.calculator.CalculatorOuterClass.NoParam) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pb.calculator.CalculatorOuterClass.NoParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pb.calculator.CalculatorOuterClass.NoParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.NoParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.calculator.CalculatorOuterClass.NoParam prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code calculator.NoParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:calculator.NoParam)
        pb.calculator.CalculatorOuterClass.NoParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_NoParam_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_NoParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.calculator.CalculatorOuterClass.NoParam.class, pb.calculator.CalculatorOuterClass.NoParam.Builder.class);
      }

      // Construct using pb.calculator.CalculatorOuterClass.NoParam.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_NoParam_descriptor;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.NoParam getDefaultInstanceForType() {
        return pb.calculator.CalculatorOuterClass.NoParam.getDefaultInstance();
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.NoParam build() {
        pb.calculator.CalculatorOuterClass.NoParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.NoParam buildPartial() {
        pb.calculator.CalculatorOuterClass.NoParam result = new pb.calculator.CalculatorOuterClass.NoParam(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.calculator.CalculatorOuterClass.NoParam) {
          return mergeFrom((pb.calculator.CalculatorOuterClass.NoParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.calculator.CalculatorOuterClass.NoParam other) {
        if (other == pb.calculator.CalculatorOuterClass.NoParam.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:calculator.NoParam)
    }

    // @@protoc_insertion_point(class_scope:calculator.NoParam)
    private static final pb.calculator.CalculatorOuterClass.NoParam DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.calculator.CalculatorOuterClass.NoParam();
    }

    public static pb.calculator.CalculatorOuterClass.NoParam getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NoParam>
        PARSER = new com.google.protobuf.AbstractParser<NoParam>() {
      @java.lang.Override
      public NoParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NoParam> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NoParam> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.calculator.CalculatorOuterClass.NoParam getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CalculationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:calculator.CalculationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 a = 1;</code>
     * @return The a.
     */
    long getA();

    /**
     * <code>int64 b = 2;</code>
     * @return The b.
     */
    long getB();
  }
  /**
   * Protobuf type {@code calculator.CalculationRequest}
   */
  public static final class CalculationRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:calculator.CalculationRequest)
      CalculationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CalculationRequest.class.getName());
    }
    // Use CalculationRequest.newBuilder() to construct.
    private CalculationRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CalculationRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.calculator.CalculatorOuterClass.CalculationRequest.class, pb.calculator.CalculatorOuterClass.CalculationRequest.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private long a_ = 0L;
    /**
     * <code>int64 a = 1;</code>
     * @return The a.
     */
    @java.lang.Override
    public long getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private long b_ = 0L;
    /**
     * <code>int64 b = 2;</code>
     * @return The b.
     */
    @java.lang.Override
    public long getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0L) {
        output.writeInt64(1, a_);
      }
      if (b_ != 0L) {
        output.writeInt64(2, b_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, a_);
      }
      if (b_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, b_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.calculator.CalculatorOuterClass.CalculationRequest)) {
        return super.equals(obj);
      }
      pb.calculator.CalculatorOuterClass.CalculationRequest other = (pb.calculator.CalculatorOuterClass.CalculationRequest) obj;

      if (getA()
          != other.getA()) return false;
      if (getB()
          != other.getB()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getA());
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getB());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.calculator.CalculatorOuterClass.CalculationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code calculator.CalculationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:calculator.CalculationRequest)
        pb.calculator.CalculatorOuterClass.CalculationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.calculator.CalculatorOuterClass.CalculationRequest.class, pb.calculator.CalculatorOuterClass.CalculationRequest.Builder.class);
      }

      // Construct using pb.calculator.CalculatorOuterClass.CalculationRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        a_ = 0L;
        b_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationRequest_descriptor;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.CalculationRequest getDefaultInstanceForType() {
        return pb.calculator.CalculatorOuterClass.CalculationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.CalculationRequest build() {
        pb.calculator.CalculatorOuterClass.CalculationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.CalculationRequest buildPartial() {
        pb.calculator.CalculatorOuterClass.CalculationRequest result = new pb.calculator.CalculatorOuterClass.CalculationRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pb.calculator.CalculatorOuterClass.CalculationRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.a_ = a_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.b_ = b_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.calculator.CalculatorOuterClass.CalculationRequest) {
          return mergeFrom((pb.calculator.CalculatorOuterClass.CalculationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.calculator.CalculatorOuterClass.CalculationRequest other) {
        if (other == pb.calculator.CalculatorOuterClass.CalculationRequest.getDefaultInstance()) return this;
        if (other.getA() != 0L) {
          setA(other.getA());
        }
        if (other.getB() != 0L) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                a_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                b_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long a_ ;
      /**
       * <code>int64 a = 1;</code>
       * @return The a.
       */
      @java.lang.Override
      public long getA() {
        return a_;
      }
      /**
       * <code>int64 a = 1;</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(long value) {

        a_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 a = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        a_ = 0L;
        onChanged();
        return this;
      }

      private long b_ ;
      /**
       * <code>int64 b = 2;</code>
       * @return The b.
       */
      @java.lang.Override
      public long getB() {
        return b_;
      }
      /**
       * <code>int64 b = 2;</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(long value) {

        b_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 b = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        b_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:calculator.CalculationRequest)
    }

    // @@protoc_insertion_point(class_scope:calculator.CalculationRequest)
    private static final pb.calculator.CalculatorOuterClass.CalculationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.calculator.CalculatorOuterClass.CalculationRequest();
    }

    public static pb.calculator.CalculatorOuterClass.CalculationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculationRequest>
        PARSER = new com.google.protobuf.AbstractParser<CalculationRequest>() {
      @java.lang.Override
      public CalculationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CalculationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.calculator.CalculatorOuterClass.CalculationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CalculationResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:calculator.CalculationResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 result = 1;</code>
     * @return The result.
     */
    long getResult();
  }
  /**
   * Protobuf type {@code calculator.CalculationResponse}
   */
  public static final class CalculationResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:calculator.CalculationResponse)
      CalculationResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        CalculationResponse.class.getName());
    }
    // Use CalculationResponse.newBuilder() to construct.
    private CalculationResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CalculationResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.calculator.CalculatorOuterClass.CalculationResponse.class, pb.calculator.CalculatorOuterClass.CalculationResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private long result_ = 0L;
    /**
     * <code>int64 result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public long getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0L) {
        output.writeInt64(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.calculator.CalculatorOuterClass.CalculationResponse)) {
        return super.equals(obj);
      }
      pb.calculator.CalculatorOuterClass.CalculationResponse other = (pb.calculator.CalculatorOuterClass.CalculationResponse) obj;

      if (getResult()
          != other.getResult()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getResult());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.CalculationResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.calculator.CalculatorOuterClass.CalculationResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code calculator.CalculationResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:calculator.CalculationResponse)
        pb.calculator.CalculatorOuterClass.CalculationResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.calculator.CalculatorOuterClass.CalculationResponse.class, pb.calculator.CalculatorOuterClass.CalculationResponse.Builder.class);
      }

      // Construct using pb.calculator.CalculatorOuterClass.CalculationResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_CalculationResponse_descriptor;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.CalculationResponse getDefaultInstanceForType() {
        return pb.calculator.CalculatorOuterClass.CalculationResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.CalculationResponse build() {
        pb.calculator.CalculatorOuterClass.CalculationResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.CalculationResponse buildPartial() {
        pb.calculator.CalculatorOuterClass.CalculationResponse result = new pb.calculator.CalculatorOuterClass.CalculationResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pb.calculator.CalculatorOuterClass.CalculationResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.calculator.CalculatorOuterClass.CalculationResponse) {
          return mergeFrom((pb.calculator.CalculatorOuterClass.CalculationResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.calculator.CalculatorOuterClass.CalculationResponse other) {
        if (other == pb.calculator.CalculatorOuterClass.CalculationResponse.getDefaultInstance()) return this;
        if (other.getResult() != 0L) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                result_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long result_ ;
      /**
       * <code>int64 result = 1;</code>
       * @return The result.
       */
      @java.lang.Override
      public long getResult() {
        return result_;
      }
      /**
       * <code>int64 result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(long value) {

        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:calculator.CalculationResponse)
    }

    // @@protoc_insertion_point(class_scope:calculator.CalculationResponse)
    private static final pb.calculator.CalculatorOuterClass.CalculationResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.calculator.CalculatorOuterClass.CalculationResponse();
    }

    public static pb.calculator.CalculatorOuterClass.CalculationResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalculationResponse>
        PARSER = new com.google.protobuf.AbstractParser<CalculationResponse>() {
      @java.lang.Override
      public CalculationResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CalculationResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalculationResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.calculator.CalculatorOuterClass.CalculationResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NumbersRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:calculator.NumbersRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 numbers = 1;</code>
     * @return A list containing the numbers.
     */
    java.util.List<java.lang.Long> getNumbersList();
    /**
     * <code>repeated int64 numbers = 1;</code>
     * @return The count of numbers.
     */
    int getNumbersCount();
    /**
     * <code>repeated int64 numbers = 1;</code>
     * @param index The index of the element to return.
     * @return The numbers at the given index.
     */
    long getNumbers(int index);
  }
  /**
   * Protobuf type {@code calculator.NumbersRequest}
   */
  public static final class NumbersRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:calculator.NumbersRequest)
      NumbersRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        NumbersRequest.class.getName());
    }
    // Use NumbersRequest.newBuilder() to construct.
    private NumbersRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NumbersRequest() {
      numbers_ = emptyLongList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_NumbersRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.calculator.CalculatorOuterClass.internal_static_calculator_NumbersRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.calculator.CalculatorOuterClass.NumbersRequest.class, pb.calculator.CalculatorOuterClass.NumbersRequest.Builder.class);
    }

    public static final int NUMBERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.LongList numbers_ =
        emptyLongList();
    /**
     * <code>repeated int64 numbers = 1;</code>
     * @return A list containing the numbers.
     */
    @java.lang.Override
    public java.util.List<java.lang.Long>
        getNumbersList() {
      return numbers_;
    }
    /**
     * <code>repeated int64 numbers = 1;</code>
     * @return The count of numbers.
     */
    public int getNumbersCount() {
      return numbers_.size();
    }
    /**
     * <code>repeated int64 numbers = 1;</code>
     * @param index The index of the element to return.
     * @return The numbers at the given index.
     */
    public long getNumbers(int index) {
      return numbers_.getLong(index);
    }
    private int numbersMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getNumbersList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(numbersMemoizedSerializedSize);
      }
      for (int i = 0; i < numbers_.size(); i++) {
        output.writeInt64NoTag(numbers_.getLong(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < numbers_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(numbers_.getLong(i));
        }
        size += dataSize;
        if (!getNumbersList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        numbersMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.calculator.CalculatorOuterClass.NumbersRequest)) {
        return super.equals(obj);
      }
      pb.calculator.CalculatorOuterClass.NumbersRequest other = (pb.calculator.CalculatorOuterClass.NumbersRequest) obj;

      if (!getNumbersList()
          .equals(other.getNumbersList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNumbersCount() > 0) {
        hash = (37 * hash) + NUMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getNumbersList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static pb.calculator.CalculatorOuterClass.NumbersRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.calculator.CalculatorOuterClass.NumbersRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code calculator.NumbersRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:calculator.NumbersRequest)
        pb.calculator.CalculatorOuterClass.NumbersRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_NumbersRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_NumbersRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.calculator.CalculatorOuterClass.NumbersRequest.class, pb.calculator.CalculatorOuterClass.NumbersRequest.Builder.class);
      }

      // Construct using pb.calculator.CalculatorOuterClass.NumbersRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        numbers_ = emptyLongList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.calculator.CalculatorOuterClass.internal_static_calculator_NumbersRequest_descriptor;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.NumbersRequest getDefaultInstanceForType() {
        return pb.calculator.CalculatorOuterClass.NumbersRequest.getDefaultInstance();
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.NumbersRequest build() {
        pb.calculator.CalculatorOuterClass.NumbersRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.calculator.CalculatorOuterClass.NumbersRequest buildPartial() {
        pb.calculator.CalculatorOuterClass.NumbersRequest result = new pb.calculator.CalculatorOuterClass.NumbersRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(pb.calculator.CalculatorOuterClass.NumbersRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          numbers_.makeImmutable();
          result.numbers_ = numbers_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.calculator.CalculatorOuterClass.NumbersRequest) {
          return mergeFrom((pb.calculator.CalculatorOuterClass.NumbersRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.calculator.CalculatorOuterClass.NumbersRequest other) {
        if (other == pb.calculator.CalculatorOuterClass.NumbersRequest.getDefaultInstance()) return this;
        if (!other.numbers_.isEmpty()) {
          if (numbers_.isEmpty()) {
            numbers_ = other.numbers_;
            numbers_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureNumbersIsMutable();
            numbers_.addAll(other.numbers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                long v = input.readInt64();
                ensureNumbersIsMutable();
                numbers_.addLong(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureNumbersIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  numbers_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.LongList numbers_ = emptyLongList();
      private void ensureNumbersIsMutable() {
        if (!numbers_.isModifiable()) {
          numbers_ = makeMutableCopy(numbers_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated int64 numbers = 1;</code>
       * @return A list containing the numbers.
       */
      public java.util.List<java.lang.Long>
          getNumbersList() {
        numbers_.makeImmutable();
        return numbers_;
      }
      /**
       * <code>repeated int64 numbers = 1;</code>
       * @return The count of numbers.
       */
      public int getNumbersCount() {
        return numbers_.size();
      }
      /**
       * <code>repeated int64 numbers = 1;</code>
       * @param index The index of the element to return.
       * @return The numbers at the given index.
       */
      public long getNumbers(int index) {
        return numbers_.getLong(index);
      }
      /**
       * <code>repeated int64 numbers = 1;</code>
       * @param index The index to set the value at.
       * @param value The numbers to set.
       * @return This builder for chaining.
       */
      public Builder setNumbers(
          int index, long value) {

        ensureNumbersIsMutable();
        numbers_.setLong(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 numbers = 1;</code>
       * @param value The numbers to add.
       * @return This builder for chaining.
       */
      public Builder addNumbers(long value) {

        ensureNumbersIsMutable();
        numbers_.addLong(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 numbers = 1;</code>
       * @param values The numbers to add.
       * @return This builder for chaining.
       */
      public Builder addAllNumbers(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, numbers_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 numbers = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumbers() {
        numbers_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:calculator.NumbersRequest)
    }

    // @@protoc_insertion_point(class_scope:calculator.NumbersRequest)
    private static final pb.calculator.CalculatorOuterClass.NumbersRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.calculator.CalculatorOuterClass.NumbersRequest();
    }

    public static pb.calculator.CalculatorOuterClass.NumbersRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NumbersRequest>
        PARSER = new com.google.protobuf.AbstractParser<NumbersRequest>() {
      @java.lang.Override
      public NumbersRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NumbersRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NumbersRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.calculator.CalculatorOuterClass.NumbersRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_NoParam_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_NoParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_CalculationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_CalculationRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_CalculationResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_CalculationResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_calculator_NumbersRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_calculator_NumbersRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/calculator.proto\022\ncalculator\"\t\n\007" +
      "NoParam\"*\n\022CalculationRequest\022\t\n\001a\030\001 \001(\003" +
      "\022\t\n\001b\030\002 \001(\003\"%\n\023CalculationResponse\022\016\n\006re" +
      "sult\030\001 \001(\003\"!\n\016NumbersRequest\022\017\n\007numbers\030" +
      "\001 \003(\0032\351\001\n\nCalculator\022H\n\003Add\022\036.calculator" +
      ".CalculationRequest\032\037.calculator.Calcula" +
      "tionResponse\"\000\022K\n\006Divide\022\036.calculator.Ca" +
      "lculationRequest\032\037.calculator.Calculatio" +
      "nResponse\"\000\022D\n\003Sum\022\032.calculator.NumbersR" +
      "equest\032\037.calculator.CalculationResponse\"" +
      "\000B \n\rpb.calculatorZ\017./pb/calculatorb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_calculator_NoParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_calculator_NoParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_NoParam_descriptor,
        new java.lang.String[] { });
    internal_static_calculator_CalculationRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_calculator_CalculationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_CalculationRequest_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_calculator_CalculationResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_calculator_CalculationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_CalculationResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_calculator_NumbersRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_calculator_NumbersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_calculator_NumbersRequest_descriptor,
        new java.lang.String[] { "Numbers", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
